# Generated by Django 5.2.6 on 2025-09-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('idUtilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('cuidUtilisateur', models.CharField(max_length=10, unique=True)),
                ('nomUtilisateur', models.CharField(max_length=255)),
                ('prenomUtilisateur', models.CharField(max_length=255)),
                ('passwordUtilisateur', models.CharField(max_length=255)),
            ],
        ),
    ]
