# Generated by Django 5.2.6 on 2025-09-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('idAgent', models.AutoField(primary_key=True, serialize=False)),
                ('cuidAgent', models.CharField(max_length=15, unique=True)),
                ('nomAgent', models.CharField(blank=True, max_length=100)),
                ('prenomAgent', models.CharField(blank=True, max_length=100)),
                ('profilAgent', models.CharField(max_length=10)),
                ('statutAgent', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('idBase', models.AutoField(primary_key=True, serialize=False)),
                ('codeIsoBase', models.CharField(max_length=4, unique=True)),
                ('libBase', models.CharField(max_length=10)),
                ('typeBase', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('idFlag', models.AutoField(primary_key=True, serialize=False)),
                ('libFlag', models.CharField(max_length=1, unique=True)),
                ('descFlag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatutAlert',
            fields=[
                ('idStatut', models.AutoField(primary_key=True, serialize=False)),
                ('libStatut', models.CharField(max_length=20, unique=True)),
                ('descStatut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrancheAge',
            fields=[
                ('idTrancheAge', models.AutoField(primary_key=True, serialize=False)),
                ('borneInferieur', models.IntegerField()),
                ('borneSuperieur', models.IntegerField()),
                ('libTrancheAge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAlerte',
            fields=[
                ('idTypeAlerte', models.AutoField(primary_key=True, serialize=False)),
                ('libTypeAlerte', models.CharField(max_length=10, unique=True)),
                ('descTypeAlerte', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('idTraitement', models.AutoField(primary_key=True, serialize=False)),
                ('dateTraitement', models.DateField()),
                ('nombreTraitement', models.IntegerField()),
                ('idAgent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.agent')),
                ('idBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.base')),
                ('idFlag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.flag')),
                ('idStatut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.statutalert')),
                ('idTypeAlerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.typealerte')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idTraitement', 'idBase', 'idFlag', 'idStatut', 'idTypeAlerte', 'idAgent', 'dateTraitement'), name='unique_cle_traitement')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idStock', models.AutoField(primary_key=True, serialize=False)),
                ('dateStock', models.DateField()),
                ('nombreStock', models.IntegerField()),
                ('idBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.base')),
                ('idFlag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.flag')),
                ('idStatut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.statutalert')),
                ('idTrancheAge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.trancheage')),
                ('idTypeAlerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingKYC.typealerte')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idStock', 'idBase', 'idFlag', 'idStatut', 'idTypeAlerte', 'idTypeAlerte', 'dateStock'), name='unique_cle_stock')],
            },
        ),
    ]
