# Generated by Django 5.2.6 on 2025-09-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingKYC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='descBase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
