# Generated by Django 5.2.6 on 2025-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingKYC', '0002_base_descbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='libFlag',
            field=models.CharField(blank=True, max_length=1, unique=True),
        ),
    ]
