# Generated by Django 5.2.6 on 2025-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingKYC', '0003_alter_flag_libflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='nomAgent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='prenomAgent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='profilAgent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='statutAgent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='libBase',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='base',
            index=models.Index(fields=['codeIsoBase'], name='reportingKY_codeIso_35e160_idx'),
        ),
    ]
